import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'pt' | 'es' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  pt: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.inbox': 'Inbox Omnichannel',
    'nav.automations': 'Automações DM',
    'nav.chat': 'Chat IA',
    'nav.creator': 'Creator Studio',
    'nav.comments': 'Comentários',
    'nav.prompts': 'Prompt Manager',
    'nav.analytics': 'Analytics',
    'nav.connections': 'Conexões',
    'nav.plans': 'Planos',
    'nav.settings': 'Configurações',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.subtitle': 'Visão geral em tempo real do seu ecossistema social',
    'dashboard.export': 'Exportar Relatório',
    'dashboard.liveMode': 'Live Mode',
    'dashboard.liveMode.on': 'Live Mode ON',
    'dashboard.exporting': 'Exportando...',
    'dashboard.metrics.aiResponse': 'Taxa de Resposta IA',
    'dashboard.metrics.messages': 'Mensagens Processadas',
    'dashboard.metrics.responseTime': 'Tempo Médio Resposta',
    'dashboard.metrics.engagement': 'Engajamento Total',
    'dashboard.metrics.today': 'Hoje',
    'dashboard.metrics.last24h': 'Últimas 24h',
    'dashboard.metrics.vsManual': 'vs. Manual: 2.5min',
    'dashboard.metrics.conversionRate': 'Taxa de conversão',
    'dashboard.insights': 'Insights IA',
    'dashboard.insights.viewAll': 'Ver Todos os Insights',
    'dashboard.activity': 'Atividade em Tempo Real',
    'dashboard.automation': 'Automação',
    'dashboard.automation.processed': 'Mensagens Processadas',
    'dashboard.automation.avgTime': 'Tempo Médio Resposta',
    'dashboard.automation.rate': 'Taxa Automação',
    'dashboard.automation.automated': 'automatizado',
    'dashboard.automation.byAi': 'pela IA',
    'dashboard.sentiment': 'Sentimento',
    'dashboard.sentiment.positive': 'Positivo',
    'dashboard.sentiment.neutral': 'Neutro',
    'dashboard.sentiment.negative': 'Negativo',
    
    // Creator Studio
    'creator.title': 'Creator Studio',
    'creator.subtitle': 'Crie conteúdo inteligente com IA',
    'creator.step1': 'Escolha o formato',
    'creator.step2': 'Selecione as plataformas',
    'creator.step3': 'Crie seu conteúdo',
    'creator.step4': 'Escreva a legenda',
    'creator.step5': 'Agende publicação',
    'creator.formats.feed': 'Feed',
    'creator.formats.stories': 'Stories',
    'creator.formats.reels': 'Reels',
    'creator.tabs.ai': 'IA',
    'creator.tabs.upload': 'Upload',
    'creator.tabs.template': 'Templates',
    'creator.ai.prompt': 'Descreva a arte que deseja criar...',
    'creator.ai.generate': 'Gerar Arte com IA',
    'creator.ai.generating': 'Gerando...',
    'creator.ai.referenceImage': 'Adicionar imagem de referência (opcional)',
    'creator.ai.referenceImageHelp': 'Use uma imagem como base para a IA',
    'creator.ai.referenceImageUploaded': 'Imagem de referência carregada!',
    'creator.ai.referenceImageRemoved': 'Referência removida',
    'creator.upload.drag': 'Arraste sua imagem ou clique para fazer upload',
    'creator.upload.button': 'Escolher Arquivo',
    'creator.templates.select': 'Selecione um template',
    'creator.caption.placeholder': 'Escreva sua legenda aqui...',
    'creator.caption.generateAi': 'Gerar com IA',
    'creator.caption.generating': 'Gerando...',
    'creator.caption.generateCaption': 'Gerar legenda',
    'creator.caption.generateHashtags': 'Gerar hashtags',
    'creator.hashtags.title': 'Hashtags Sugeridas',
    'creator.hashtags.generate': 'Gerar Hashtags',
    'creator.cover.title': 'Capa do Post (Opcional)',
    'creator.cover.add': 'Adicionar imagem de capa',
    'creator.cover.description': 'Imagem principal do post',
    'creator.cover.uploaded': 'Capa carregada!',
    'creator.cover.removed': 'Capa removida',
    'creator.schedule.selectDate': 'Selecione a data',
    'creator.schedule.selectTime': 'Selecione o horário',
    'creator.suggestions.bestTime': 'Melhor Horário',
    'creator.suggestions.engagement': 'Engajamento Previsto',
    'creator.publish': 'Agendar Publicação',
    'creator.publishing': 'Agendando...',
    'creator.publishNow': 'Publicar Agora',
    'creator.scheduled': 'Posts Agendados',
    'creator.scheduled.empty': 'Nenhum post agendado',
    'creator.scheduled.delete': 'Remover',
    
    // Plans
    'plans.title': 'Transforme Seguidores em Clientes',
    'plans.subtitle': 'Automatize suas vendas no Instagram, WhatsApp e mais com IA',
    'plans.proof': '+2.500 empresas já aumentaram suas vendas em até 300% com Social Flow',
    'plans.stats.increase': 'Aumento médio em vendas',
    'plans.stats.companies': 'Empresas confiam',
    'plans.stats.support': 'Atendimento automático',
    'plans.stats.uptime': 'Uptime garantido',
    'plans.month': '/mês',
    'plans.tokens': 'tokens/mês',
    'plans.current': '✓ Plano Atual',
    'plans.subscribe': 'Assinar Agora',
    'plans.subscribeNow': '🚀 Começar Agora - 30% OFF',
    'plans.popular': 'Mais Popular',
    'plans.extras': 'Packs Extras',
    'plans.extras.soon': 'Em breve',
    'plans.extras.contact': 'Fale conosco',
    'plans.extras.custom': 'Custom',
    'plans.testimonials': 'O que nossos clientes dizem',
    'plans.faq': 'Perguntas Frequentes',
    'plans.faq.cancel': 'Posso cancelar quando quiser?',
    'plans.faq.cancelAnswer': 'Sim! Sem fidelidade. Cancele quando quiser pelo painel.',
    'plans.faq.tech': 'Preciso de conhecimento técnico?',
    'plans.faq.techAnswer': 'Zero! Interface super intuitiva. Configura em 5 minutos.',
    'plans.cta.title': 'Pronto para 3x suas vendas?',
    'plans.cta.subtitle': 'Junte-se a 2.500+ empresas que já transformaram suas vendas',
    'plans.cta.button': '🚀 Começar Agora - 30% OFF',
    'plans.cta.features': '✓ Sem fidelidade  ✓ Cancelamento simples  ✓ Suporte 24/7',
    
    // Common
    'common.save': 'Salvar',
    'common.cancel': 'Cancelar',
    'common.loading': 'Carregando...',
    'common.success': 'Sucesso!',
    'common.error': 'Erro',
    'common.delete': 'Excluir',
    'common.edit': 'Editar',
    'common.view': 'Ver',
    'common.send': 'Enviar',
    'common.close': 'Fechar',
  },
  es: {
    // Navigation
    'nav.dashboard': 'Panel',
    'nav.inbox': 'Bandeja Omnicanal',
    'nav.automations': 'Automatizaciones DM',
    'nav.chat': 'Chat IA',
    'nav.creator': 'Creator Studio',
    'nav.comments': 'Comentarios',
    'nav.prompts': 'Gestor de Prompts',
    'nav.analytics': 'Analíticas',
    'nav.connections': 'Conexiones',
    'nav.plans': 'Planes',
    'nav.settings': 'Configuración',
    
    // Dashboard
    'dashboard.title': 'Panel de Control',
    'dashboard.subtitle': 'Visión general en tiempo real de tu ecosistema social',
    'dashboard.export': 'Exportar Informe',
    'dashboard.liveMode': 'Modo en Vivo',
    'dashboard.liveMode.on': 'Modo en Vivo ON',
    'dashboard.exporting': 'Exportando...',
    'dashboard.metrics.aiResponse': 'Tasa de Respuesta IA',
    'dashboard.metrics.messages': 'Mensajes Procesados',
    'dashboard.metrics.responseTime': 'Tiempo Medio Respuesta',
    'dashboard.metrics.engagement': 'Engagement Total',
    'dashboard.metrics.today': 'Hoy',
    'dashboard.metrics.last24h': 'Últimas 24h',
    'dashboard.metrics.vsManual': 'vs. Manual: 2.5min',
    'dashboard.metrics.conversionRate': 'Tasa de conversión',
    'dashboard.insights': 'Insights IA',
    'dashboard.insights.viewAll': 'Ver Todos los Insights',
    'dashboard.activity': 'Actividad en Tiempo Real',
    'dashboard.automation': 'Automatización',
    'dashboard.automation.processed': 'Mensajes Procesados',
    'dashboard.automation.avgTime': 'Tiempo Medio Respuesta',
    'dashboard.automation.rate': 'Tasa Automatización',
    'dashboard.automation.automated': 'automatizado',
    'dashboard.automation.byAi': 'por la IA',
    'dashboard.sentiment': 'Sentimiento',
    'dashboard.sentiment.positive': 'Positivo',
    'dashboard.sentiment.neutral': 'Neutro',
    'dashboard.sentiment.negative': 'Negativo',
    
    // Creator Studio
    'creator.title': 'Creator Studio',
    'creator.subtitle': 'Crea contenido inteligente con IA',
    'creator.step1': 'Elige el formato',
    'creator.step2': 'Selecciona las plataformas',
    'creator.step3': 'Crea tu contenido',
    'creator.step4': 'Escribe la leyenda',
    'creator.step5': 'Programa publicación',
    'creator.formats.feed': 'Feed',
    'creator.formats.stories': 'Stories',
    'creator.formats.reels': 'Reels',
    'creator.tabs.ai': 'IA',
    'creator.tabs.upload': 'Subir',
    'creator.tabs.template': 'Plantillas',
    'creator.ai.prompt': 'Describe el arte que deseas crear...',
    'creator.ai.generate': 'Generar Arte con IA',
    'creator.ai.generating': 'Generando...',
    'creator.ai.referenceImage': 'Agregar imagen de referencia (opcional)',
    'creator.ai.referenceImageHelp': 'Usa una imagen como base para la IA',
    'creator.ai.referenceImageUploaded': '¡Imagen de referencia cargada!',
    'creator.ai.referenceImageRemoved': 'Referencia eliminada',
    'creator.upload.drag': 'Arrastra tu imagen o haz clic para subir',
    'creator.upload.button': 'Elegir Archivo',
    'creator.templates.select': 'Selecciona una plantilla',
    'creator.caption.placeholder': 'Escribe tu leyenda aquí...',
    'creator.caption.generateAi': 'Generar con IA',
    'creator.caption.generating': 'Generando...',
    'creator.caption.generateCaption': 'Generar leyenda',
    'creator.caption.generateHashtags': 'Generar hashtags',
    'creator.hashtags.title': 'Hashtags Sugeridos',
    'creator.hashtags.generate': 'Generar Hashtags',
    'creator.cover.title': 'Portada del Post (Opcional)',
    'creator.cover.add': 'Agregar imagen de portada',
    'creator.cover.description': 'Imagen principal del post',
    'creator.cover.uploaded': '¡Portada cargada!',
    'creator.cover.removed': 'Portada eliminada',
    'creator.schedule.selectDate': 'Selecciona la fecha',
    'creator.schedule.selectTime': 'Selecciona la hora',
    'creator.suggestions.bestTime': 'Mejor Horario',
    'creator.suggestions.engagement': 'Engagement Previsto',
    'creator.publish': 'Programar Publicación',
    'creator.publishing': 'Programando...',
    'creator.publishNow': 'Publicar Ahora',
    'creator.scheduled': 'Posts Programados',
    'creator.scheduled.empty': 'No hay posts programados',
    'creator.scheduled.delete': 'Eliminar',
    
    // Plans
    'plans.title': 'Transforma Seguidores en Clientes',
    'plans.subtitle': 'Automatiza tus ventas en Instagram, WhatsApp y más con IA',
    'plans.proof': '+2.500 empresas ya aumentaron sus ventas hasta 300% con Social Flow',
    'plans.stats.increase': 'Aumento promedio en ventas',
    'plans.stats.companies': 'Empresas confían',
    'plans.stats.support': 'Atención automática',
    'plans.stats.uptime': 'Uptime garantizado',
    'plans.month': '/mes',
    'plans.tokens': 'tokens/mes',
    'plans.current': '✓ Plan Actual',
    'plans.subscribe': 'Suscribirse Ahora',
    'plans.subscribeNow': '🚀 Comenzar Ahora - 30% OFF',
    'plans.popular': 'Más Popular',
    'plans.extras': 'Packs Extras',
    'plans.extras.soon': 'Próximamente',
    'plans.extras.contact': 'Contáctanos',
    'plans.extras.custom': 'Personalizado',
    'plans.testimonials': 'Lo que dicen nuestros clientes',
    'plans.faq': 'Preguntas Frecuentes',
    'plans.faq.cancel': '¿Puedo cancelar cuando quiera?',
    'plans.faq.cancelAnswer': '¡Sí! Sin fidelidad. Cancela cuando quieras desde el panel.',
    'plans.faq.tech': '¿Necesito conocimientos técnicos?',
    'plans.faq.techAnswer': '¡Cero! Interfaz súper intuitiva. Configura en 5 minutos.',
    'plans.cta.title': '¿Listo para 3x tus ventas?',
    'plans.cta.subtitle': 'Únete a 2.500+ empresas que ya transformaron sus ventas',
    'plans.cta.button': '🚀 Comenzar Ahora - 30% OFF',
    'plans.cta.features': '✓ Sin fidelidad  ✓ Cancelación simple  ✓ Soporte 24/7',
    
    // Common
    'common.save': 'Guardar',
    'common.cancel': 'Cancelar',
    'common.loading': 'Cargando...',
    'common.success': '¡Éxito!',
    'common.error': 'Error',
    'common.delete': 'Eliminar',
    'common.edit': 'Editar',
    'common.view': 'Ver',
    'common.send': 'Enviar',
    'common.close': 'Cerrar',
  },
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.inbox': 'Omnichannel Inbox',
    'nav.automations': 'DM Automations',
    'nav.chat': 'AI Chat',
    'nav.creator': 'Creator Studio',
    'nav.comments': 'Comments',
    'nav.prompts': 'Prompt Manager',
    'nav.analytics': 'Analytics',
    'nav.connections': 'Connections',
    'nav.plans': 'Plans',
    'nav.settings': 'Settings',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.subtitle': 'Real-time overview of your social ecosystem',
    'dashboard.export': 'Export Report',
    'dashboard.liveMode': 'Live Mode',
    'dashboard.liveMode.on': 'Live Mode ON',
    'dashboard.exporting': 'Exporting...',
    'dashboard.metrics.aiResponse': 'AI Response Rate',
    'dashboard.metrics.messages': 'Messages Processed',
    'dashboard.metrics.responseTime': 'Average Response Time',
    'dashboard.metrics.engagement': 'Total Engagement',
    'dashboard.metrics.today': 'Today',
    'dashboard.metrics.last24h': 'Last 24h',
    'dashboard.metrics.vsManual': 'vs. Manual: 2.5min',
    'dashboard.metrics.conversionRate': 'Conversion rate',
    'dashboard.insights': 'AI Insights',
    'dashboard.insights.viewAll': 'View All Insights',
    'dashboard.activity': 'Real-Time Activity',
    'dashboard.automation': 'Automation',
    'dashboard.automation.processed': 'Messages Processed',
    'dashboard.automation.avgTime': 'Average Response Time',
    'dashboard.automation.rate': 'Automation Rate',
    'dashboard.automation.automated': 'automated',
    'dashboard.automation.byAi': 'by AI',
    'dashboard.sentiment': 'Sentiment',
    'dashboard.sentiment.positive': 'Positive',
    'dashboard.sentiment.neutral': 'Neutral',
    'dashboard.sentiment.negative': 'Negative',
    
    // Creator Studio
    'creator.title': 'Creator Studio',
    'creator.subtitle': 'Create smart content with AI',
    'creator.step1': 'Choose format',
    'creator.step2': 'Select platforms',
    'creator.step3': 'Create your content',
    'creator.step4': 'Write caption',
    'creator.step5': 'Schedule publication',
    'creator.formats.feed': 'Feed',
    'creator.formats.stories': 'Stories',
    'creator.formats.reels': 'Reels',
    'creator.tabs.ai': 'AI',
    'creator.tabs.upload': 'Upload',
    'creator.tabs.template': 'Templates',
    'creator.ai.prompt': 'Describe the artwork you want to create...',
    'creator.ai.generate': 'Generate Art with AI',
    'creator.ai.generating': 'Generating...',
    'creator.ai.referenceImage': 'Add reference image (optional)',
    'creator.ai.referenceImageHelp': 'Use an image as a base for the AI',
    'creator.ai.referenceImageUploaded': 'Reference image uploaded!',
    'creator.ai.referenceImageRemoved': 'Reference removed',
    'creator.upload.drag': 'Drag your image or click to upload',
    'creator.upload.button': 'Choose File',
    'creator.templates.select': 'Select a template',
    'creator.caption.placeholder': 'Write your caption here...',
    'creator.caption.generateAi': 'Generate with AI',
    'creator.caption.generating': 'Generating...',
    'creator.caption.generateCaption': 'Generate caption',
    'creator.caption.generateHashtags': 'Generate hashtags',
    'creator.hashtags.title': 'Suggested Hashtags',
    'creator.hashtags.generate': 'Generate Hashtags',
    'creator.cover.title': 'Post Cover (Optional)',
    'creator.cover.add': 'Add cover image',
    'creator.cover.description': 'Main post image',
    'creator.cover.uploaded': 'Cover uploaded!',
    'creator.cover.removed': 'Cover removed',
    'creator.schedule.selectDate': 'Select date',
    'creator.schedule.selectTime': 'Select time',
    'creator.suggestions.bestTime': 'Best Time',
    'creator.suggestions.engagement': 'Predicted Engagement',
    'creator.publish': 'Schedule Publication',
    'creator.publishing': 'Scheduling...',
    'creator.publishNow': 'Publish Now',
    'creator.scheduled': 'Scheduled Posts',
    'creator.scheduled.empty': 'No scheduled posts',
    'creator.scheduled.delete': 'Remove',
    
    // Plans
    'plans.title': 'Turn Followers into Customers',
    'plans.subtitle': 'Automate your sales on Instagram, WhatsApp and more with AI',
    'plans.proof': '+2,500 companies have already increased their sales by up to 300% with Social Flow',
    'plans.stats.increase': 'Average sales increase',
    'plans.stats.companies': 'Companies trust us',
    'plans.stats.support': 'Automatic support',
    'plans.stats.uptime': 'Guaranteed uptime',
    'plans.month': '/month',
    'plans.tokens': 'tokens/month',
    'plans.current': '✓ Current Plan',
    'plans.subscribe': 'Subscribe Now',
    'plans.subscribeNow': '🚀 Get Started Now - 30% OFF',
    'plans.popular': 'Most Popular',
    'plans.extras': 'Extra Packs',
    'plans.extras.soon': 'Coming soon',
    'plans.extras.contact': 'Contact us',
    'plans.extras.custom': 'Custom',
    'plans.testimonials': 'What our customers say',
    'plans.faq': 'Frequently Asked Questions',
    'plans.faq.cancel': 'Can I cancel anytime?',
    'plans.faq.cancelAnswer': 'Yes! No commitment. Cancel anytime from the dashboard.',
    'plans.faq.tech': 'Do I need technical knowledge?',
    'plans.faq.techAnswer': 'Zero! Super intuitive interface. Set up in 5 minutes.',
    'plans.cta.title': 'Ready to 3x your sales?',
    'plans.cta.subtitle': 'Join 2,500+ companies that have already transformed their sales',
    'plans.cta.button': '🚀 Get Started Now - 30% OFF',
    'plans.cta.features': '✓ No commitment  ✓ Simple cancellation  ✓ 24/7 Support',
    
    // Common
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.loading': 'Loading...',
    'common.success': 'Success!',
    'common.error': 'Error',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.view': 'View',
    'common.send': 'Send',
    'common.close': 'Close',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'pt';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    console.log('Mudando idioma para:', lang);
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    // 1) Direct lookup for flat keys like 'nav.dashboard'
    const flat = (translations as any)[language]?.[key];
    if (typeof flat === 'string') return flat;

    // 2) Fallback to nested lookup (future-proofing if we nest later)
    const parts = key.split('.');
    let cur: any = (translations as any)[language];
    for (const p of parts) cur = cur?.[p];
    return typeof cur === 'string' ? cur : key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}
