// Supabase Edge Function para gerar imagens de exemplo
// Versão simplificada que não depende de API externa

import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

serve(async (req) => {
  // Handle CORS preflight requests
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders });
  }

  try {
    const { prompt } = await req.json();
    
    console.log('Recebido prompt:', prompt);

    if (!prompt) {
      throw new Error('Prompt é obrigatório');
    }

    // Criar uma imagem SVG simples baseada no prompt
    console.log('Gerando imagem SVG...');
    
    // Limitar o tamanho do prompt e remover caracteres problemáticos
    const safePrompt = prompt.replace(/[^\x00-\x7F]/g, ''); // Remove caracteres não-ASCII
    const displayPrompt = safePrompt.length > 40 ? safePrompt.substring(0, 40) + '...' : safePrompt;
    
    // Criar um hash simples para variação de cores baseado no prompt
    const hash = safePrompt.split('').reduce((acc, char) => acc + char.charCodeAt(0), 0);
    const hue1 = hash % 360;
    const hue2 = (hash + 120) % 360;
    
    // Criar SVG com apenas caracteres ASCII
    const svgContent = `<?xml version="1.0" encoding="UTF-8"?>
<svg width="1080" height="1080" xmlns="http://www.w3.org/2000/svg">
  <defs>
    <linearGradient id="grad1" x1="0%" y1="0%" x2="100%" y2="100%">
      <stop offset="0%" style="stop-color:hsl(${hue1}, 70%, 50%);stop-opacity:1" />
      <stop offset="100%" style="stop-color:hsl(${hue2}, 70%, 50%);stop-opacity:1" />
    </linearGradient>
    <radialGradient id="grad2" cx="50%" cy="50%" r="50%" fx="50%" fy="50%">
      <stop offset="0%" style="stop-color:white;stop-opacity:0.3" />
      <stop offset="100%" style="stop-color:white;stop-opacity:0" />
    </radialGradient>
  </defs>
  <rect width="100%" height="100%" fill="url(#grad1)"/>
  <circle cx="540" cy="400" r="200" fill="url(#grad2)"/>
  
  <rect x="90" y="500" width="900" height="180" rx="20" fill="rgba(0,0,0,0.3)"/>
  <text x="540" y="570" font-family="Arial, sans-serif" font-size="36" fill="white" text-anchor="middle" font-weight="bold">
    "${displayPrompt}"
  </text>
  
  <text x="540" y="650" font-family="Arial, sans-serif" font-size="24" fill="white" text-anchor="middle" opacity="0.8">
    Generated by AI
  </text>
  
  <text x="540" y="700" font-family="Arial, sans-serif" font-size="18" fill="white" text-anchor="middle" opacity="0.6">
    ${new Date().toISOString().split('T')[0]}
  </text>
</svg>`;

    // Usar TextEncoder para converter para UTF-8 e depois base64
    const encoder = new TextEncoder();
    const data = encoder.encode(svgContent);
    
    // Converter para base64 de forma segura
    let binary = '';
    for (let i = 0; i < data.length; i++) {
      binary += String.fromCharCode(data[i]);
    }
    const base64Svg = btoa(binary);
    
    console.log('Imagem SVG gerada com sucesso');

    return new Response(
      JSON.stringify({
        image: `data:image/svg+xml;base64,${base64Svg}`,
        prompt: prompt,
        timestamp: new Date().toISOString(),
        note: "Imagem gerada localmente"
      }),
      {
        headers: {
          ...corsHeaders,
          'Content-Type': 'application/json',
        },
        status: 200,
      }
    );

  } catch (error) {
    console.error('Erro na Edge Function:', error);
    
    return new Response(
      JSON.stringify({ 
        error: error.message || 'Erro desconhecido',
        details: error.toString(),
        suggestion: "Verifique se o prompt contém apenas caracteres básicos"
      }),
      {
        headers: {
          ...corsHeaders,
          'Content-Type': 'application/json',
        },
        status: 500,
      }
    );
  }
});